medicalLessThanFiveYears: 0.6
medicalFromFiveToEightYears: 0.8
medicalLessThanEightYears: 1
experienceLessThanFiveYears: 5.0
experienceFromFiveToEightYears: 8.0
ageMax: 70
phoneNumberLength: 11
tax: 0.13

logging:
  level:
    ru.podgoretskaya: DEBUG